evo_config:
  _target_: shinka.core.EvolutionConfig
  patch_types:
    - "full"
    - "diff"
  patch_type_probs:
    - 0.5
    - 0.5
  num_generations: 10
  max_parallel_jobs: 2
  max_patch_attempts: 10
  num_branches_per_generation: 2
  llm_models:
    - "gemini-2.5-flash"
  llm_dynamic_selection: null
  embedding_model: "gemini-embedding-001"
  results_dir: ${output_dir}
  async_llm_client_kwargs:
    max_parallel_queries: 3
    min_seconds_between_api_requests: 10


